### ISSUE TITLE
How to read Trajectory Points when they are executed by Moveit2

### ISSUE THREAD

**Issue by alexlt97** [ros-planning/moveit2_tutorials#156]
### Description
We were trying the tutorials of Moveit2 with the panda robot and we would like to see the list of points generated to achieve the final position of the trajectory. In Moveit1 once the plan is executed you could read the trajectory points from the topic **/robot/robot_joint_trajectory_controller/follow_joint_trajectory/goal**. How can we achieve the same results in Moveit2? We were trying to echo the visualization topic  **/display_plan_path** that RVIZ used to display these points. However, we didn't receive any msg from echo and the msg used in  **/display_plan_path** is moveit_msgs/msg/DisplayTrajectory so it should show these points.

How is the right way of reading these points in Moveit2?

### Your environment
* ROS Distro: Foxy
* OS Version: e.g. Ubuntu 20.04
* Source

**Comment by tylerjw** [comment]
@MarqRazz weren't you thinking about this recently?  Do you have an idea for how this feature could be added?

**Comment by MarqRazz** [comment]
I was looking into this and also ran into the same issue of not being able to listen to action topics like you can in ROS1. As a work around I was also planing on listening to the DisplayTrajectory topic but have not had a chance to test it. You can see that the tutorials are able to visualize the plan, are you sure you are listening on the correct topic?

After I pulled my workspace up to date I found that the DisplayTrajectory is being published on the topic `/display_planned_path`
you can run `ros2 topic echo /display_planned_path` to view it in the terminal.

**Comment by alexlt97** [comment]
Yes indeed after we had a proper controller I was able echo /display_planned_path. However, our final approach will be using moveit2 without RVIZ, so using /display_planned_path is not a final solution. At the moment we are trying to implement the output of the planned trajectory from the code source of the follow_joint_trajectory_controller_handle.cpp. Which is part of moveit_simple_controller_manager. We are trying to implement our own moveit_simple_controller_manager but we are having some issues exporting the plugin[our_moveit_simple_controller_manager]. 

![WhatsApp Image 2021-11-02 at 09 21 41](https://user-images.githubusercontent.com/48478107/139810769-f44d1b5e-4662-4e11-a30d-2098684c89aa.jpeg)

We followed moveit_simple_controller_manager structure as an example, where we think our XML and CMakeList files are correct, so maybe our issue remains where to declare the new plugin. Is there any documentation to help us?

**Comment by vatanaksoytezer** [comment]
> Yes indeed after we had a proper controller I was able echo /display_planned_path. However, our final approach will be using moveit2 without RVIZ, so using /display_planned_path is not a final solution.

RViz is just for displays, `/display_planned_path` will be published any way so you can use it.

**Comment by destogl** [comment]
> We followed moveit_simple_controller_manager structure as an example, where we think our XML and CMakeList files are correct, so maybe our issue remains where to declare the new plugin. Is there any documentation to help us?

This usually happens if the plugin is not exported properly. How does your `pluginlib_export_plugin_description_file()` in CMakeLists.txt looks like? The essential part is the first argument.

**Comment by alexlt97** [comment]
We included: moveit_core ${package_name} ${our_movveit_simple_controller_manager_plugin_description.xml} 
Now it works, we might think the issue was that we used colcon build --packages-select so we only build ${package_name}.
