### ISSUE TITLE
execution tolerances in controller.yaml

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit2_tutorials#167]
### Description

Is this line still correct:

> If you want to configure the execution tolerances, you will have to edit the `controller.yaml` file if using a FollowJointTrajectory controller, or manually add it into the generated trajectory message from the planner.

Located at the end of this tutorial: http://moveit2_tutorials.picknik.ai/doc/move_group_interface/move_group_interface_tutorial.html

**Comment by jackcenter** [comment]
It doesn't look like you can send execution tolerances from the generated trajectory message. At least I didn't see anything to that effect looking through `moveit_msgs::msg::RobotTrajectory`

You can set constraints in ros2_control through the controller.yaml file still. For the ros2_control_demos I think something like this would work:
```
forward_position_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
    interface_name: position

    constraints:
      goal_time: 1.0                   # Defaults to zero
      stopped_velocity_tolerance: 0.02 # Defaults to 0.01
      joint1:
        trajectory: 0.05               # Defaults to zero (ie. the tolerance is not enforced)
        goal:       0.03               # Defaults to zero (ie. the tolerance is not enforced)
      joint2:
        goal:       0.01
```
So I think it should be changed to just say: "If you want to configure the execution tolerances, you will have to edit the controller.yaml file."
