### ISSUE TITLE
Joint Limits are not included in tutorial launch files

### ISSUE THREAD

**Issue by vatanaksoytezer** [ros-planning/moveit2_tutorials#185]
Basically what the title says. We should consider joint limits read from the config file of the robots in the tutorials.

**Comment by sea-bass** [comment]
Bumping this issue, because I was just testing something on the latest moveit2 branch and one of our most basic examples:

```
ros2 launch moveit_resources_panda_moveit_config demo.launch.py
```

has errors about required parameters for the panda config.

```
[rviz2-1] [ERROR] [1679761789.691008064] [moveit_trajectory_processing.time_optimal_trajectory_generation]: No acceleration limit was defined for joint panda_joint1! You have to define acceleration limits in the URDF or joint_limits.yaml
```

**Comment by AndyZe** [comment]
I actually don't see that error?! I have the `main` or `ros2` branches of moveit2, moveit2_tutorials, and moveit_resources.

**Comment by AndyZe** [comment]
Closed by https://github.com/ros-planning/moveit_resources/pull/165

**Comment by sea-bass** [comment]
Sorry, the issue was in moveit_resources, but not this repo. I forgot to amend this. Thanks, Andy!
