### ISSUE TITLE
Graph_msgs missing from tutorials

### ISSUE THREAD

**Issue by stephanie-eng** [ros-planning/moveit2_tutorials#188]
### Description
When running this command:
```rosdep install -r --from-paths . --ignore-src --rosdistro $ROS_DISTRO -y```

Got the following error:

```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
moveit2_tutorials: Cannot locate rosdep definition for [gripper_controllers]
moveit_visual_tools: Cannot locate rosdep definition for [graph_msgs]
```

**Comment by vatanaksoytezer** [comment]
Thanks a lot for the issue and the fix @stephanie-eng!

Though, it seems like I can both install graph_msgs and gripper controllers via apt-get:

```
sudo apt-get install ros-foxy-gripper-controllers
sudo apt-get install ros-foxy-graph-msgs
```

Can you try running and sudo apt-get update and trying again?

Can you also confirm you can run the same commands?

**Comment by vatanaksoytezer** [comment]
@stephanie-eng let me know if we should close the issue.

**Comment by stephanie-eng** [comment]
This issue still exists in the main branch as there is no package for ros-galactic-graph-msgs

**Comment by vatanaksoytezer** [comment]
Seems like graph_msgs is already released though: https://github.com/ros/rosdistro/pull/30780 and CI could install it sucesfully: https://github.com/ros-planning/moveit2_tutorials/runs/4094661154?check_suite_focus=true#step:6:195. I'll check this out.

**Comment by stephanie-eng** [comment]
After the latest sync, this issue is now resolved.
