### ISSUE TITLE
Create installation, tutorials, and concepts top level organization

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit2_tutorials#203]
### Description

I'd like there to be top-level organization to the tutorials page in order to provide more organization and a space for more concepts or contributor-focused content on the documentation website.

### Motivation
The https://docs.ros.org/en/foxy/index.html website has different subsections for installation, tutorials, concepts, contributing, and other top-level pages.  It would be nice if the moveit2 documentation included other sections that could be used for content that wasn't necessarily pointed at new users (as the tutorials are).

**Comment by sjahr** [comment]
Done :heavy_check_mark:
