### ISSUE TITLE
Update README to guide users trying to build locally.

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit2_tutorials#207]
### Description

As pointed out by this issue: https://github.com/ros-planning/moveit2_tutorials/issues/206#issuecomment-969016351

If a user follows the instructions in the README for building the tutorials locally on foxy it will not work.  The readme should make it really clear which version of ROS they target with links at the top to the other branches.  Secondly, the README in each ros version should just link to the "Getting Started" page for building the tutorials in a ros workspace if that branch is deployed.  That'll avoid the README from getting out of date.

**Comment by vatanaksoytezer** [comment]
I think the instructions are already updated.
