### ISSUE TITLE
External links have two slashes

### ISSUE THREAD

**Issue by stephanie-eng** [ros-planning/moveit2_tutorials#214]
### Description
Minor issue, the external links are not broken, but they all have two slashes in them after the ros distro, for example, the link to move_group_interface from the first link on the Move Group C++ Interface page is:

https://github.com/ros-planning/moveit2/blob/foxy//moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h

The link still works regardless.

**Comment by JafarAbdi** [comment]
Fixed by https://github.com/ros-planning/moveit2_tutorials/pull/217
