### ISSUE TITLE
Clean, test and move run_ompl_constrained_planning to tutorials repository

### ISSUE THREAD

**Issue by vatanaksoytezer** [ros-planning/moveit2_tutorials#237]
There are plenty of unnecessary stuff in https://github.com/ros-planning/moveit2/tree/4cbd1a767630c3a98eeef8e91cb0fc8627f57c94/moveit_demo_nodes/run_ompl_constrained_planning and has been untested for a while. We should test, clean and move this to tutorials repository.

**Comment by sjahr** [comment]
Done with https://moveit.picknik.ai/main/doc/how_to_guides/using_ompl_constrained_planning/ompl_constrained_planning.html
