### ISSUE TITLE
Deploy doxygen site for MoveIt2

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit2_tutorials#253]
For my bio_ik fork, I deployed a Doxygen site using some cmake and a GitHub action.  Here are some links to the relevant files.  Something similar should be possible in MoveIt:

* Deployed Doxygen site: https://tylerjw.github.io/bio_ik/
* CMake function for enabling Doxygen: https://github.com/tylerjw/bio_ik/blob/ros2/cmake/Doxygen.cmake
* Root CMakeLists.txt where Doxygen function is called: https://github.com/tylerjw/bio_ik/blob/d7687deceeea923e21fb4716120f5fcc1a70dd08/CMakeLists.txt#L35-L37
* GitHub action for deploying site: https://github.com/tylerjw/bio_ik/blob/ros2/.github/workflows/doxygen.yaml

**Comment by senceryazici** [comment]
I think this is completed in #310 by @vatanaksoytezer and should be closed. Here is the [site](http://moveit.picknik.ai/galactic/api/html/index.html) for MoveIt2 API
