### ISSUE TITLE
Write How-To Guide for Contributing Doxygen Comments

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit2_tutorials#254]
Currently, MoveIt uses multiple styles of Doxygen comments.  It would be really nice if we had a guide that recommended some tooling to create standardized Doxygen comments.  This would provide an easy way for people to make useful contributions to MoveIt.  Here are some tools that could be used to automate adding comments that use specific styles:

* SublimeText: https://packagecontrol.io/packages/DoxyDoxygen
* VSCode: https://marketplace.visualstudio.com/items?itemName=cschlosser.doxdocgen
* VIM: https://www.vim.org/scripts/script.php?script_id=987

Ideally, we could have a config for each of these that would generate the same standardized style of Doxygen comments.  We should also have some basic guidance on how one should write useful Doxygen comments.  This page should either include or link to the page on generating the Doxygen site locally.

**Comment by henrygerardmoore** [comment]
Working on this
