### ISSUE TITLE
README Directory Structure is out of date

### ISSUE THREAD

**Issue by stephanie-eng** [ros-planning/moveit2_tutorials#290]
### Description

Since #251 restructured the tutorials, the directory structure changed. The Directory Structure of the README refers to the old structure, which is out of date and should be updated.

**Comment by senceryazici** [comment]
After chatting with @tylerjw , since the directory structure related stuff are already described in website now, he is in favor of removing the section completely from the README.md

**Comment by senceryazici** [comment]
I've opened a PR for this #315
