### ISSUE TITLE
Disable + reactivate Show Trail makes rviz crash

### ISSUE THREAD

**Issue by relffok** [ros-planning/moveit2_tutorials#331]
### Description

Hello, I am not sure in which repo to post this and since this has happened during checking out the tutorial maybe somebody can link me to the right repo. 

When I disable Show Trail and don't replan before enabling it again, rviz crashes.

### Your environment
* ROS Distro: Galactic
* OS Version: Ubuntu 20.04
* Source Build
* source commit: 97dea6d

### Steps to reproduce
Follow the steps of the visualization tutorial: 
    ros2 launch moveit2_tutorials demo.launch.py rviz_tutorial:=true
Section:
https://moveit.picknik.ai/galactic/doc/tutorials/quickstart_in_rviz/quickstart_in_rviz_tutorial.html#step-4-use-motion-planning-with-the-panda

* Enable Show Trail
* Plan a trajectory 
* Uncheck Show Trail
* Check Show Trail again

rviz crashes.

### Expected behaviour

rviz should not crash.

### Backtrace or Console output
`[rviz2-1]   what():  ItemIdentityException: Material with the name package://moveit_resources_panda_description/meshes/visual/link6.daeMaterial141120Robot already exists. in ResourceManager::add at /tmp/binarydeb/ros-galactic-rviz-ogre-vendor-8.5.0/obj-x86_64-linux-gnu/ogre-v1.12.1-prefix/src/ogre-v1.12.1/OgreMain/src/OgreResourceManager.cpp (line 148)`

**Comment by stephanie-eng** [comment]
I believe this is an RViz bug - see the fix here: https://github.com/ros2/rviz/pull/811

The fix may not be in your Rviz version - can you check the date with the following?
```sudo apt list | grep ros-galactic-rviz-default-plugins```

If this is indeed the issue, you can work around it by building Rviz from source
