### ISSUE TITLE
do the step on "Getting Started doc", get the error on step "colcon build --mixin release"

### ISSUE THREAD

**Issue by samping** [ros-planning/moveit2_tutorials#332]
### Description

Overview of your issue here.

### Your environment
* ROS Distro: Foxy 
* OS Version:  Ubuntu 20.04
* Source 

### Steps to reproduce
do the step on Getting Started doc

### Expected behaviour
Download MoveIt 2 Tutorials Source
do the step :
colcon build --mixin release

### Backtrace or Console output

Starting >>> moveit_core
--- stderr: moveit_core                                 
/home/hsp/ws_moveit2/src/moveit2/moveit_core/robot_state/src/robot_state.cpp: In member function ‘void moveit::core::RobotState::printStatePositionsWithJointLimits(const moveit::core::JointModelGroup*, std::ostream&) const’:
/home/hsp/ws_moveit2/src/moveit2/moveit_core/robot_state/src/robot_state.cpp:2109:40: error: ‘setprecision’ is not a member of ‘std’
 2109 |     out << "   " << std::fixed << std::setprecision(5) << bound.min_position_ << "\t";
      |                                        ^~~~~~~~~~~~
/home/hsp/ws_moveit2/src/moveit2/moveit_core/robot_state/src/robot_state.cpp:2129:40: error: ‘setprecision’ is not a member of ‘std’
 2129 |     out << " \t" << std::fixed << std::setprecision(5) << bound.max_position_ << "  \t" << joint->getName()
      |                                        ^~~~~~~~~~~~
/home/hsp/ws_moveit2/src/moveit2/moveit_core/robot_state/src/robot_state.cpp:2130:47: error: ‘setprecision’ is not a member of ‘std’
 2130 |         << " current: " << std::fixed << std::setprecision(5) << current_value << '\n';
      |                                               ^~~~~~~~~~~~
/home/hsp/ws_moveit2/src/moveit2/moveit_core/robot_state/src/robot_state.cpp: In function ‘void moveit::core::{anonymous}::getPoseString(std::ostream&, const Isometry3d&, const string&)’:
/home/hsp/ws_moveit2/src/moveit2/moveit_core/robot_state/src/robot_state.cpp:2247:18: error: ‘setw’ is not a member of ‘std’; did you mean ‘set’?
 2247 |       ss << std::setw(8) << pose(y, x) << " ";
      |                  ^~~~
      |                  set
/home/hsp/ws_moveit2/src/moveit2/moveit_core/robot_state/src/robot_state.cpp: In member function ‘void moveit::core::RobotState::getStateTreeJointString(std::ostream&, const moveit::core::JointModel*, const string&, bool) const’:
/home/hsp/ws_moveit2/src/moveit2/moveit_core/robot_state/src/robot_state.cpp:2266:52: error: ‘setw’ is not a member of ‘std’; did you mean ‘set’?
 2266 |     ss << pfx << jm->getVariableNames()[i] << std::setw(12) << position_[jm->getFirstVariableIndex() + i] << '\n';
      |                                                    ^~~~
      |                                                    set
make[2]: *** [robot_state/CMakeFiles/moveit_robot_state.dir/build.make:89: robot_state/CMakeFiles/moveit_robot_state.dir/src/robot_state.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1827: robot_state/CMakeFiles/moveit_robot_state.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< moveit_core [10.1s, exited with code 2]

Summary: 10 packages finished [16.7s]
  1 package failed: moveit_core
  1 package had stderr output: moveit_core
  34 packages not processed

**Comment by harunuz** [comment]
Hi, I encountered the same issue. The issue is closed so I assume you solved it. Can you please tell me how you did it?
