### ISSUE TITLE
RViz window does not open

### ISSUE THREAD

**Issue by nandbert** [ros-planning/moveit2_tutorials#334]
### Description

I am trying to run the very first tutorial according to https://moveit.picknik.ai/foxy/doc/quickstart_in_rviz/quickstart_in_rviz_tutorial.html

When I execute
```$ ros2 launch moveit2_tutorials demo.launch.py rviz_tutorial:=true```
the rviz splash screen appears and disappears, and I can see rviz in the process list, but it does not open the main window

Starting rviz manually with ```rviz2``` works just fine

### Your environment
* ROS Distro: foxy
* OS Version: Ubuntu 20.04
* Binary build

(So far, I have also tried galactic binary, and foxy source builds of moveit and rviz, same result)

### Steps to reproduce
see above

### Expected behaviour
RViz opens a window and lets my plan interactively (like it worked w/ ROS1)

### Backtrace or Console output

https://gist.github.com/nandbert/89ee811fcc4fce7de8dd2ee195305e5a

**Comment by vatanaksoytezer** [comment]
@nandbert sorry this got missed. Are you still having issues?

**Comment by tylerjw** [comment]
Closing as this is really old. Please re-open if you are still experiencing this.

**Comment by nandbert** [comment]
It is still the same issue. Meanwhile I can produce it also with the humble tutorial docker container:

```
$ docker run --rm -it --net host --privileged -v /tmp/.X11-unix:/tmp/.X11-unix -v $XAUTHORITY:/root/.Xauthority -e QT_X11_NO_MITSHM=1 -e DISPLAY=$DISPLAY -e NVIDIA_VISIBLE_DEVICES=all -v NVIDIA_DRIVER_CAPABILITIES=all ghcr.io/ros-planning/moveit2_tutorials:humble-tutorial /bin/bash
root@mobl4: ~/ws_moveit# . /opt/ros/humble/setup.bash 
root@mobl4: ~/ws_moveit# . install/setup.bash 
root@mobl4: ~/ws_moveit# ros2 launch moveit2_tutorials demo.launch.py rviz_config:=panda_moveit_config_demo_empty.rviz
```

Full log is here [https://gist.github.com/nandbert/15a18b6acfea9ff6c787fd20d27a1de4](url)

Can you please re-open? (I cannot, I am not a collaborator)

**Comment by nandbert** [comment]
Problem finally understood, main window opens, but outside the visible area of my desktop (fvwm2). No idea why this happens, and only with RViz in the MoveIt2 tutorial, but I finally found the window :-)
