### ISSUE TITLE
Error Build Moveit2_Tutorials

### ISSUE THREAD

**Issue by yangxuan1032** [ros-planning/moveit2_tutorials#347]
### Description

When I build the moveit2_tutorial, it has some errors.
Running the `colcon build --event-handlers desktop_notification- status- --cmake-args -DCMAKE_BUILD_TYPE=Release
`returns the following while building moveit_visual_tools
`--- stderr: moveit_visual_tools
CMake Error at CMakeLists.txt:52 (add_executable):
  Target "moveit_visual_tools_demo" links to target
  "libstatistics_collector::libstatistics_collector_test_msgs__rosidl_generator_c"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:52 (add_executable):
  Target "moveit_visual_tools_demo" links to target
  "libstatistics_collector::libstatistics_collector_test_msgs__rosidl_typesupport_introspection_c"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:52 (add_executable):
  Target "moveit_visual_tools_demo" links to target
  "libstatistics_collector::libstatistics_collector_test_msgs__rosidl_typesupport_c"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:39 (add_library):
  Target "moveit_visual_tools" links to target
  "libstatistics_collector::libstatistics_collector_test_msgs__rosidl_generator_cpp"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:39 (add_library):
  Target "moveit_visual_tools" links to target
  "libstatistics_collector::libstatistics_collector_test_msgs__rosidl_typesupport_introspection_cpp"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:39 (add_library):
  Target "moveit_visual_tools" links to target
  "libstatistics_collector::libstatistics_collector_test_msgs__rosidl_typesupport_cpp"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?`

### Your environment
* ROS Distro: Foxy
* OS Version: e.g. Ubuntu 20.04
* Source  build

### Steps to reproduce
Follow along with the tutorials at https://github.com/ros-planning/moveit2_tutorials

### Expected behaviour
moveit_tutorials and its contemporary packages should have been built successfully.

**Comment by JafarAbdi** [comment]
I'm pretty sure this's due to previous build artifacts, doing a clean rebuild should fix it
