### ISSUE TITLE
Dead link in examples

### ISSUE THREAD

**Issue by stephanie-eng** [ros-planning/moveit2_tutorials#452]
### Description

The [Motion planning pipeline example](https://moveit.picknik.ai/humble/doc/examples/motion_planning_pipeline/motion_planning_pipeline_tutorial.html#running-the-code) has a dead link in it. If you click on the `Visualization Tutorial` link, it takes you to the following page:

https://moveit.picknik.ai/doc/tutorials/quickstart_in_rviz/quickstart_in_rviz_tutorial.html#rviz-visual-tools

**Comment by sjahr** [comment]
Seems to now
