### ISSUE TITLE
Improving Moveit2 documentation for Windows

### ISSUE THREAD

**Issue by ferraridamiano** [ros-planning/moveit2_tutorials#457]
MoveIt2 claims to support Windows but the documentations, tutorials and examples works out of the box just with Ubuntu

**Comment by vatanaksoytezer** [comment]
We have a small documentation in the website: https://moveit.ros.org/install-moveit2/binary-windows/. Tagging @lilustga to see if you have some more documentation, maybe also including the other distros as well.

**Comment by tylerjw** [comment]
Windows is not supported. Tutorials for Windows are welcome but will be difficult for us to review as none of the maintainers develop on Windows.
