### ISSUE TITLE
How-to section, malformed table of contents

### ISSUE THREAD

**Issue by lorepieri8** [ros-planning/moveit2_tutorials#487]
https://moveit.picknik.ai/humble/doc/how_to_guides/how_to_guides.html

1. I'm not able to locate the gamepad tutorial introduced in #461
2. The table of contents is pulling sections (such as Learning Objectives, Instructions, Further Reading) from this article: https://moveit.picknik.ai/humble/doc/how_to_guides/how_to_write_doxygen.html

**Comment by vatanaksoytezer** [comment]
That tutorial exists in the main branch (latest version) of documentation,located here: https://moveit.picknik.ai/main/doc/how_to_guides/controller_teleoperation/controller_teleoperation.html?highlight=gamepad
