### ISSUE TITLE
Not able to build for deploy

### ISSUE THREAD

**Issue by auman66** [ros-planning/moveit2_tutorials#49]
https://github.com/ros-planning/moveit2_tutorials/blob/6ebdf086c344b26ed38b9dec8bc8a4ead07b4754/.travis.yml#L16

To build the pages Melodic or Noetic is needed since `rosdocs-lite` is not yet available for Foxy. Is this the reason that the code if failing to deploy?

This will not be caught on CI until a branch is merged in and travis attempts to deploy to gh-pages branch.

**Comment by vatanaksoytezer** [comment]
Closing this since #75 enables to build and deploy to website.
