### ISSUE TITLE
Change Pandas Arm to Universal Robot -Motion Planing API

### ISSUE THREAD

**Issue by LucaBross** [ros-planning/moveit2_tutorials#534]
### Description
I want to do the Motion Planing API Example. There i want to change the Pandas Arm to the Universal Robots Arm UR3e without a tool. 

### Your environment
* ROS Distro: Humble
* OS Version: Ubuntu 22.04

### Steps to reproduce
I copied the sourcecode of the [Motion Planing Api Example](https://github.com/ros-planning/moveit2_tutorials/blob/main/doc/examples/motion_planning_api/src/motion_planning_api_tutorial.cpp). There i changed all the `Planing Group`to ` ur_manipulator`.  I also changed all the `panda_link0` to `base_link` and all the `panda_link8` to `wrist_3_link`.
I also copied the [CMakeLists](https://github.com/ros-planning/moveit2_tutorials/blob/main/doc/examples/motion_planning_api/CMakeLists.txt) and changed to according to my package and file 
The files are in ~/ws_moveit2/src/simple_pick_place_ur

### Console output
When i try to build the package i get the error: 
```
fatal error: pluginlib/class_loader.hpp: No such file or directory
1 | #include <pluginlib/class_loader.hpp>
```

How can i solve this? Do i need to add anything else to the CMakeList?

**Comment by tylerjw** [comment]
It would be really nice to have tutorials for using a UR with the tutorials. I'm sorry we were not able to reproduce this error.
