### ISSUE TITLE
404 on link to launch file in 'move_group_interface_tutorial' for Foxy

### ISSUE THREAD

**Issue by darshan-k-s** [ros-planning/moveit2_tutorials#557]
### Description
Dead link on the moveit2 foxy tutorials at `https://moveit.picknik.ai/foxy/doc/move_group_interface/move_group_interface_tutorial.html`, in `The Launch File` section. 

### Your environment
* ROS Distro: Foxy
* OS Version: Ubuntu 20.04
* On the hosted [web page](https://moveit.picknik.ai/foxy/doc/move_group_interface/move_group_interface_tutorial.html)

### Steps to reproduce
Just open the link on the hosted page to realise it. Upon building the tutorials locally, it only opens up Rolling tutorials, even with the foxy branch.

### Expected behaviour
Should open the `move_group_interface_tutorial.launch.py` file on GitHub. 

### Output

![Screenshot from 2022-12-19 16-21-47](https://user-images.githubusercontent.com/77616581/208409720-cd922cee-0d78-47aa-b10d-87fb3ec7ebe4.png)

![404](https://user-images.githubusercontent.com/77616581/208408862-67c8ea82-1842-45e4-85f6-dad143676f1d.png)

**Comment by henningkayser** [comment]
Thanks for reporting! Foxy is not supported anymore, it has also been removed from the tutorials. Note that there has been a rework of a lot of the URLs somewhat recently. The launch file is reachable for the current versions, so I'm closing this.
