### ISSUE TITLE
cannot build moveit2 tutorials (maybe qt linking error)

### ISSUE THREAD

**Issue by ajseo95** [ros-planning/moveit2_tutorials#558]
### Description

Cant build moveit2 tutorial from [Getting Started](https://moveit.picknik.ai/foxy/doc/getting_started/getting_started.html) guide

### Your environment
* ROS Distro: Foxy
* OS Version: Ubuntu 20.04 focal
* Source or Binary build? try to build tutorial source in introduction page

### Steps to reproduce
source /opt/ros/foxy/setup.bash

sudo apt install python3-rosdep

sudo rosdep init
rosdep update
sudo apt update
sudo apt dist-upgrade

sudo apt install python3-colcon-common-extensions
sudo apt install python3-colcon-mixin
colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
colcon mixin update default

sudo apt install python3-vcstool

mkdir -p ~/ws_moveit2/src

cd ~/ws_moveit2/src
git clone https://github.com/ros-planning/moveit2_tutorials.git -b foxy --depth 1
vcs import < moveit2_tutorials/moveit2_tutorials.repos

sudo apt update && rosdep install -r --from-paths . --ignore-src --rosdistro $ROS_DISTRO -y

cd ~/ws_moveit2
colcon build --mixin release

### Expected behaviour
build success

### Backtrace or Console output

Starting >>> rviz_visual_tools
--- stderr: rviz_visual_tools                                
CMake Warning at CMakeLists.txt:77 (add_library):
  Cannot generate a safe runtime search path for target rviz_visual_tools_gui
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libfreetype.so.6] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/ahjeong/anaconda3/envs/rds-env/lib
    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/ahjeong/anaconda3/envs/rds-env/lib

  Some of these libraries may not be found correctly.

---
Finished <<< rviz_visual_tools [22.9s]
Starting >>> moveit_visual_tools
--- stderr: moveit_visual_tools                                
CMake Warning at CMakeLists.txt:39 (add_library):
  Cannot generate a safe runtime search path for target moveit_visual_tools
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libfreetype.so.6] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/ahjeong/anaconda3/envs/rds-env/lib
    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/ahjeong/anaconda3/envs/rds-env/lib

  Some of these libraries may not be found correctly.

CMake Warning at CMakeLists.txt:52 (add_executable):
  Cannot generate a safe runtime search path for target
  moveit_visual_tools_demo because files in some directories may conflict
  with libraries in implicit directories:

    runtime library [libfreetype.so.6] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/ahjeong/anaconda3/envs/rds-env/lib
    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/ahjeong/anaconda3/envs/rds-env/lib

  Some of these libraries may not be found correctly.

/usr/bin/ld: /opt/ros/foxy/lib/librviz_common.so: undefined reference to `QTreeView::verticalScrollbarValueChanged(int)@Qt_5'
/usr/bin/ld: /opt/ros/foxy/lib/librviz_default_plugins.so: undefined reference to `qt_version_tag@Qt_5.12'
/usr/bin/ld: /opt/ros/foxy/lib/librviz_common.so: undefined reference to `QTreeWidgetItem::setHidden(bool)@Qt_5'
/usr/bin/ld: /opt/ros/foxy/lib/librviz_common.so: undefined reference to `QAbstractItemView::eventFilter(QObject*, QEvent*)@Qt_5'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/moveit_visual_tools_demo.dir/build.make:440: moveit_visual_tools_demo] Error 1
make[1]: *** [CMakeFiles/Makefile2:165: CMakeFiles/moveit_visual_tools_demo.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
---
Failed   <<< moveit_visual_tools [24.1s, exited with code 2]

Summary: 1 package finished [47.3s]
  1 package failed: moveit_visual_tools
  2 packages had stderr output: moveit_visual_tools rviz_visual_tools
  1 package not processed

**Comment by henningkayser** [comment]
Foxy is EOL and the tutorials have been removed. Please consider switching to Humble or Rolling, and let us know if you find any new issues there.
