### ISSUE TITLE
In the moveit_cpp tutorial, the display of the robot never changes

### ISSUE THREAD

**Issue by AndyZe** [ros-planning/moveit2_tutorials#561]
### Description

Uncommenting [this line](https://github.com/ros-planning/moveit2_tutorials/blob/2720b86f222d1ddeb23768e5e19da99f4e9f5657/doc/examples/moveit_cpp/src/moveit_cpp_tutorial.cpp#L113):

```
    /* Uncomment if you want to execute the plan */
    planning_components->execute(); // Execute the plan
```

Does not cause any visual change in RViz. However, I can tell that the robot actually does move by watching `ros2 topic echo /joint_states`. I guess a robot_state_publisher node ought to be added to the launch file.

**Comment by henningkayser** [comment]
@AndyZe did you get to find the reason for this? If it's the PlanningScene display in RViz, maybe it's just a misconfigured topic
