### ISSUE TITLE
Migrate From `panda_moveit_config` to `moveit_resources_panda_moveit_config`

### ISSUE THREAD

**Issue by DLu** [ros-planning/moveit2_tutorials#59]
### Description

As discussed here: https://github.com/ros-planning/moveit2_tutorials/blob/main/package.xml#L40-L43

Blocks a bunch of other tutorials.

**Comment by sea-bass** [comment]
I think the bigger blocking change for the tutorials is this:

https://github.com/ros-planning/moveit_resources/issues/40

**Comment by 130s** [comment]
> As discussed here: https://github.com/ros-planning/moveit2_tutorials/blob/main/package.xml#L40-L43

For the record I _think_ those lines refer to https://github.com/ros-planning/moveit2_tutorials/blob/6ebdf086c344b26ed38b9dec8bc8a4ead07b4754/package.xml#L40-L43, the commit before https://github.com/ros-planning/moveit2_tutorials/pull/61 was merged.
