### ISSUE TITLE
MoveIt Python API execute() documentation inconsistencies?

### ISSUE THREAD

**Issue by cpr-fer** [ros-planning/moveit2_tutorials#643]
### Description

While the node and jupyter examples show the use of the execute() function like this:
```
moveit = MoveItPy(node_name="moveit_py")
moveit.execute(robot_trajectory, blocking=True, controllers=[])
```
the [.rst file](https://github.com/ros-planning/moveit2_tutorials/blob/main/doc/examples/motion_planning_python_api/motion_planning_python_api_tutorial.rst#single-pipeline-planning---default-configurations) shows
```
moveit = MoveItPy(node_name="moveit_py")
panda_arm = moveit.get_planning_component("panda_arm")
panda_arm.execute()
```

The second option does not work for me and I could not find any bindings in the files for this. 

I am not sure if this is an issue with the documentation or me using the Python API under humble. In the second case it seems a bit confusing to have two options and not explain the difference between the two execution() calls.

### Your environment
* ROS Distro: Humble
* OS Version:  Ubuntu 22.04
* Source build from main branch

### Steps to reproduce
I copy and pasted the example code for pose goals from the .rst file. If required I can provide a minimal (non-)working example with a full log output.

### Expected behaviour
The same behaviour as when running the example code.

### Backtrace or Console output

The resulting error is:

```
AttributeError: 'moveit.planning.PlanningComponent' object has no attribute 'execute'
```

**Comment by sea-bass** [comment]
This should be fixed by https://github.com/ros-planning/moveit2_tutorials/pull/629 ... we'll be getting this merged in soon, apologies!

**Comment by peterdavidfagan** [comment]
Thanks for flagging this @cpr-fer and @sea-bass and @adlarkin for reviewing and merging.
