### ISSUE TITLE
Your First C++ MoveIt Project IS NOT WORKING

### ISSUE THREAD

**Issue by MuhammedErkam** [ros-planning/moveit2_tutorials#676]
### Description

I am new at moveit2.  I am using this code -> https://moveit.picknik.ai/humble/doc/tutorials/your_first_project/your_first_project.html#plan-and-execute-using-movegroupinterface . But I have this error below :

### Your environment
* ROS Distro: ROS2 Foxy
* OS Version: Ubuntu 20.04
I have sourced moveit2 directly like this :  git clone https://github.com/ros-planning/moveit2_tutorials -b foxy --depth 1

### Steps to reproduce
Tell us how to reproduce this issue. Attempt to provide a working demo, perhaps using Docker.

### Expected behaviour
Normally, this works and panda_arm should move and I could see it on rviz2.

### Backtrace or Console output

`[INFO] [1683541079.897863548] [moveit_rdf_loader.rdf_loader]: Robot model parameter not found! Did you remap 'robot_description'?

[FATAL] [1683541079.898045469] [move_group_interface]: Unable to construct robot model. Please make sure all needed information is on the parameter server.
terminate called after throwing an instance of 'std::runtime_error'
what(): Unable to construct robot model. Please make sure all needed information is on the parameter server.
`

**Comment by henningkayser** [comment]
@MuhammedErkam please try a current ROS distribution, Rolling or Humble. Foxy is not supported anymore

**Comment by BingLee75** [comment]
If any one know how to solve this problem.
log:
```bash
# demo log
[rviz2-1] [INFO] [1684813527.398605644] [interactive_marker_display_94417594791968]: Sending request for interactive markers                           
[rviz2-1] [INFO] [1684813527.463249776] [interactive_marker_display_94417594791968]: Service response received for initialization
[rviz2-1] [INFO] [1684813530.612668544] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Stopping planning scene monitor                      [rviz2-1] [WARN] [1684813537.856027392] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with 
the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregi
ster the publisher, preventing any further logs for that name from being published on the rosout topic.
```

```bash
# hello moveit log
[INFO] [1684752797.515617587] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.0582478 seconds
[INFO] [1684752797.515663958] [moveit_robot_model.robot_model]: Loading robot model 'panda'...
[WARN] [1684752797.520957314] [moveit_ros.robot_model_loader]: No kinematics plugins defined. Fill and load kinematics.yaml!
[INFO] [1684752797.527580706] [move_group_interface]: Ready to take commands for planning group panda_arm.
[INFO] [1684752797.527955865] [hello_moveit.remote_control]: RemoteControl Ready.
[INFO] [1684752797.527982486] [hello_moveit.remote_control]: Waiting to continue: Press 'Next' in the RvizVisualToolsGui window to plan
[INFO] [1684752802.188209902] [hello_moveit.remote_control]: ... continuing                                                                              
[INFO] [1684752802.189457822] [move_group_interface]: MoveGroup action client/server read
```

**Comment by henningkayser** [comment]
I just ran the hello_world tutorial using MoveIt's main branch on Humble and didn't have any issues. The first log indicates that you have multiple node instances running, possibly from previous attempts. Please check `ros2 node list` and make sure to cancel duplicate instances before starting the demo.

Also, make sure that you are not interfering with other ROS nodes in the same local network by setting the [ROS_DOMAIN_ID](https://docs.ros.org/en/humble/Concepts/About-Domain-ID.html).

**Comment by sjahr** [comment]
The tutorial should work, please re-open this issue if you still have problems
