### ISSUE TITLE
Planning For Differential-Drive Mobile Base and an Arm

### ISSUE THREAD

**Issue by miso037** [ros-planning/moveit2_tutorials#703]
### Description

Hello.
I want to just ask if it is possible to create motion plans for Arm on a mobile base with MoveIt2 right now. I have already tried following the [Planning For Differential-Drive Mobile Base and an Arm](https://moveit.picknik.ai/main/doc/examples/mobile_base_arm/mobile_base_arm_tutorial.html) with no success.

I do not need to use the stretch robot necessarily. I was thinking of developing a very simple differential-drive platform using the ros2_control diff drive controller. The panda manipulator would be then attached to this platform.

The tutorial mentions Setting up IK solver for mobile-base and arm[](https://moveit.picknik.ai/main/doc/examples/mobile_base_arm/mobile_base_arm_tutorial.html#setting-up-ik-solver-for-mobile-base-and-arm). Is it possible to use kinematics plugins from MoveIt2, such as kdl_kinematics_plugin/KDLKinematicsPlugin?

Are there any more changes needed that are not included in the [Planning For Differential-Drive Mobile Base and an Arm](https://moveit.picknik.ai/main/doc/examples/mobile_base_arm/mobile_base_arm_tutorial.html) tutorial?

Lastly, is there any other tutorial explaining this problem?

Thank you for your answers.

### Your environment
* ROS Distro: Rolling
* OS Version: e.g. Ubuntu 22.04
* Source

**Comment by tylerjw** [comment]
That tutorial references work that has lots of outstanding issues. We would really like to have moveit working well with mobile bases but at this time more work needs to be done to support that. You are welcome to work on that problem if you would like.
