### ISSUE TITLE
realtime_servo can not control by keyboard input. fixed in local test

### ISSUE THREAD

**Issue by lilinxin75** [ros-planning/moveit2_tutorials#709]
### Description

When I try to build and run realtime  servo example with humble branch. 
can not run and fix by this way.

### Your environment
* ROS Distro: [Humble]
* OS Version: Debian 11
* Source build
* adf4c26b2f9a4392adee9510e6fb8717a104e362

### Steps to reproduce
Tell us how to reproduce this issue. Attempt to provide a working demo, perhaps using Docker.
1. comment control pub

```c++
# moveit2_tutorials/doc/examples/realtime_servo/src/servo_cpp_interface_demo.cpp
# Line  188
 //rclcpp::TimerBase::SharedPtr timer = node_->create_wall_timer(50ms, publishCommands);
```
2. fix key board input publisher define

```c++
# moveit2_tutorials/doc/examples/realtime_servo/src/servo_keyboard_input.cpp
# Line 70 71
const std::string TWIST_TOPIC = "/servo_demo_node/delta_twist_cmds";
const std::string JOINT_TOPIC = "/servo_demo_node/delta_joint_cmds";
```

### Expected behaviour
after fix in this way. arm can control by keyboard.

**Comment by ibrahiminfinite** [comment]
This issue is also outdated by the Servo refactor.
@sjahr
