### ISSUE TITLE
Incorrect Place Poses Generated in MTC Tutorial

### ISSUE THREAD

**Issue by sea-bass** [ros-planning/moveit2_tutorials#723]
### Description

I found an issue in the [MTC tutorial](https://moveit.picknik.ai/main/doc/tutorials/pick_and_place_with_moveit_task_constructor/pick_and_place_with_moveit_task_constructor.html), where the place pose generated is rotated and translated incorrectly even though we're just asking to [only translate in the Y direction by 0.5 meters](https://github.com/ros-planning/moveit2_tutorials/blob/main/doc/tutorials/pick_and_place_with_moveit_task_constructor/src/mtc_node.cpp#L287-L291).

### Your environment
* ROS Distro: Humble and Rolling (tested on both)
* OS Version: Ubuntu 22.04
* Source build

### Steps to reproduce
If you look at the marker at the pick pose:
![image](https://github.com/ros-planning/moveit2_tutorials/assets/4603398/32c00ecf-dc15-4f62-9032-d16802da0bb0)

Then the place pose RViz marker is correct, but the target object pose and plan is incorrect.
![image](https://github.com/ros-planning/moveit2_tutorials/assets/4603398/843cd2dc-23c9-46fc-87fe-dc79b74f38f0)

Is this a bug with `GeneratePlacePose` stage that was introduced at some point? Or is something misconfigured with the monitored stage?

**Comment by sea-bass** [comment]
I can fix the issue and restore it to what the video looks like by changing [this line](https://github.com/ros-planning/moveit2_tutorials/blob/humble/doc/tutorials/pick_and_place_with_moveit_task_constructor/src/mtc_node.cpp#L300)

from

```
      wrapper->setIKFrame(hand_frame);
```

to

```
      wrapper->setIKFrame(grasp_frame_transform, hand_frame);
```

to match with the IK frame set in the grasp generation stage.

This meant elevating the scope of the `grasp_frame_transform` to higher up in the demo... is this the right fix? Would appreciate input from someone more MTC savvy.

**Comment by rhaschke** [comment]
Actually, it should work to simply use the object frame:
`wrapper->setIKFrame("object")`

**Comment by sea-bass** [comment]
Sure enough, that does work -- thank you! PR incoming.
