### ISSUE TITLE
Humble branch breaks Python API and default version

### ISSUE THREAD

**Issue by henningkayser** [ros-planning/moveit2_tutorials#729]
Deploying from the humble switches the default version to "Humble" and removes the Python bindings. We don't want that, so either we have to trigger a `main` build when we push to `humble`, or we disable humble deployment completely, replacing it with a chron job. (this issue has also been brought up here #715)

**Comment by henningkayser** [comment]
I just triggered a build from main to fix the deployed version temporarily.

**Comment by tylerjw** [comment]
I opened two PRs in an attempt to fix this problem:

- https://github.com/ros-planning/moveit2_tutorials/pull/757
- https://github.com/ros-planning/moveit2_tutorials/pull/758
