### ISSUE TITLE
How to make .DAE file？I only have STL file

### ISSUE THREAD

**Issue by zouzhe1** [ros-planning/moveit2_tutorials#765]
How to make .DAE file？I  have solidworks file.

i can export stl  file   from SW.
i can use SW_to_URDF  tool    export   STL file.(mesh file  is empty)
but  i cant  export  DAE  file.

please  help me

**Comment by sea-bass** [comment]
[Blender](https://www.blender.org/) is a magical tool that can convert anything -- would suggest looking into that!
