### ISSUE TITLE
how to use moveit with gazebo

### ISSUE THREAD

**Issue by wxydejoy** [ros-planning/moveit2_tutorials#787]
### Description

how to use moveit with gazebo

### Your environment
* ROS Distro: humble
* OS Version:  Ubuntu 22.04
*  Binary build
### Please give me some help

I only found https://github.com/lbr-stack/lbr_fri_ros2_stack

**Comment by Robotawi** [comment]
I was thinking of explaining MoveIt 2 & Gazebo (Fortress) integration as a sub-task of porting the [Multiple Robot Arms Tutorial](https://ros-planning.github.io/moveit_tutorials/doc/multiple_robot_arms/multiple_robot_arms_tutorial.html) to ROS 2. [This issue](https://github.com/ros-planning/moveit2_tutorials/issues/556) is related. The integration can be separated from the multiple arms tutorial to make it easier to understand. I will be able to dedicate time to this very soon.

**Comment by wxydejoy** [comment]
thanks， Wish you all the best.
