### ISSUE TITLE
No kinematics plugins defined

### ISSUE THREAD

**Issue by Nielk7991** [ros-planning/moveit2_tutorials#815]
### Description
Hello everyone
I'm currently trying to plan a path for a pose using the hello moveit tutorial. Unfortunately, it always happens that no kinematic plugins are defined and the path planning stops.
I saw an issue about this and tried to fix it that way. However, it doesn't help if I call the node and call the kinematics.yaml in the parameters
This is the example how I tried to fixed it.
https://github.com/ros-planning/moveit2_tutorials/blob/main/doc/examples/move_group_interface/launch/move_group_interface_tutorial.launch.py

### Your environment
* ROS Distro: [Humble
* OS Version: Ubuntu 22.04
*  Binary build
* If binary, which release version?

### Steps to reproduce
I went through the setup assistant step by step and configured my URDF. Afterwards I adapted my demo launch which is as follows:
from launch import LaunchDescription
from launch_ros.actions import Node
from moveit_configs_utils import MoveItConfigsBuilder
from moveit_configs_utils.launches import generate_demo_launch
from launch.substitutions import PathJoinSubstitution
from launch_ros.substitutions import FindPackageShare

def generate_launch_description():
    # ... (Dein bisheriger Code bleibt unverändert)

    moveit_config = (MoveItConfigsBuilder("threedof_manipulator", package_name="moveit_endeffektor")
        .robot_description(file_path="config/threedof_manipulator.urdf.xacro")
        .robot_description_semantic(file_path="config/threedof_manipulator.srdf")
       # .robot_description_kinematics(file_path="config/kinematics.yaml")
        .planning_pipelines(
                pipelines=["ompl", "pilz_industrial_motion_planner", "chomp"],
                default_planning_pipeline="ompl",
            )
        .to_moveit_configs()
    )

    # Node für move_group_interface_tutorial
    move_group_demo = Node(
        name="hello_moveit",
        package="path_planner",
        executable="DummyNode",
        output="screen",
        parameters=[
            moveit_config.robot_description_kinematics,
        ],
    )

    # Füge die Nodes zur Launch-Beschreibung hinzu
    return LaunchDescription([generate_demo_launch(moveit_config), move_group_demo])

### Expected behaviour
I want to send a Pose to my Moveit which will then plan a path for the joints

### Backtrace or Console output
For the Node:
[DummyNode-8] [WARN] [1699986750.922330646] [moveit_ros.robot_model_loader]: No kinematics plugins defined. Fill and load kinematics.yaml!
[DummyNode-8] [INFO] [1699986779.258699667] [move_group_interface]: Ready to take commands for planning group Arm.
[DummyNode-8] [INFO] [1699986779.258779256] [move_group_interface]: MoveGroup action client/server ready
[move_group-3] [INFO] [1699986779.259937407] [moveit_move_group_default_capabilities.move_action_capability]: Received request
[DummyNode-8] [INFO] [1699986779.260274815] [move_group_interface]: Planning request accepted
[move_group-3] [INFO] [1699986779.260282412] [moveit_move_group_default_capabilities.move_action_capability]: executing..
[move_group-3] [INFO] [1699986779.266656808] [moveit_move_group_default_capabilities.move_action_capability]: Planning request received for MoveGroup action. Forwarding to planning pipeline.
[move_group-3] [INFO] [1699986779.267405156] [moveit.ompl_planning.model_based_planning_context]: Planner configuration 'Arm[RRTstarkConfigDefault]' will use planner 'geometric::RRTstar'. Additional configuration parameters will be set when the planner is constructed.
[rviz2-4] [INFO] [1699986779.310657015] [move_group_interface]: Ready to take commands for planning group Arm.
[move_group-3] [WARN] [1699986784.267838919] [ompl]: ./src/ompl/tools/multiplan/src/ParallelPlan.cpp:138 - ParallelPlan::solve(): Unable to find solution by any of the threads in 5.000193 seconds
[move_group-3] [INFO] [1699986784.358803715] [moveit.ompl_planning.model_based_planning_context]: Unable to solve the planning problem
[move_group-3] [INFO] [1699986784.358861872] [moveit_move_group_default_capabilities.move_action_capability]: Catastrophic failure
[DummyNode-8] [INFO] [1699986784.360475603] [move_group_interface]: Planning request aborted
[rviz2-4] [INFO] [1699986784.361429888] [moveit_ros_visualization.motion_planning_frame]: group Arm
[DummyNode-8] [ERROR] [1699986784.362546859] [move_group_interface]: MoveGroupInterface::plan() failed or timeout reached
[DummyNode-8] [ERROR] [1699986784.363325268] [hello_moveit]: Planning failed!
[INFO] [DummyNode-8]: process has finished cleanly [pid 74971]

**Comment by sjahr** [comment]
Looks like your using a custom robot `threedof_manipulator`. You'll need to create a valid config package e.g. with the [MoveIt Setup Assistant ](https://moveit.picknik.ai/main/doc/examples/setup_assistant/setup_assistant_tutorial.html?highlight=setup%20assistant) and define the kinematics plugins and groups e.g. [like here](https://github.com/ros-planning/moveit_resources/blob/ros2/panda_moveit_config/config/kinematics.yaml). Feel free to re-open this is issue if you run into any problems
