### ISSUE TITLE
i cannot successfully run "ros2 launch moveit2_tutorials motion_planning_pipeline_tutorial.launch.py",The terminal shows file was not found in the share

### ISSUE THREAD

**Issue by yangming517** [ros-planning/moveit2_tutorials#880]
### Your environment
* ROS Distro: [Humble]
* OS Version: Ubuntu 22.04
* Source or Binary build?
* If binary, which release version?
* If source, which git commit or tag?

### Description
I followed the offcial tutorial:getting started [https://moveit.picknik.ai/main/doc/tutorials/tutorials.html](url)
However, the following operations are different from the official ones
git clone https://github.com/ros-planning/moveit2_tutorials **-b humble** 
colcon build **--cmake-args -DCMAKE_BUILD_TYPE=Release --parallel-workers 1**

Obviously,command with "-b humble" will result in missing some  packages,such as 
"motion_planning_pipeline、parallel planning...."。I want to know if humble doesn't support these packages or these functions?

Because if I execute the  command "git clone https://github.com/ros-planning/moveit2_tutorials" without "-b humble"
The process that colcon build will fail.

The terminal shows that:
ym@ym-PC:~/ws_moveit2test2$ colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release --parallel-workers 1
Starting >>> moveit_common
Finished <<< moveit_common [0.20s]                   
Starting >>> moveit_msgs
Finished <<< moveit_msgs [2.21s]                      
Starting >>> moveit_configs_utils
--- stderr: moveit_configs_utils                    
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
---
Finished <<< moveit_configs_utils [0.78s]
Starting >>> moveit_resources_panda_description
Finished <<< moveit_resources_panda_description [0.19s]                   
Starting >>> moveit_resources_panda_moveit_config
Finished <<< moveit_resources_panda_moveit_config [0.20s]                   
Starting >>> moveit_resources_fanuc_description
Finished <<< moveit_resources_fanuc_description [0.20s]                   
Starting >>> moveit_resources_fanuc_moveit_config
Finished <<< moveit_resources_fanuc_moveit_config [0.20s]                   
Starting >>> robotiq_description
Finished <<< robotiq_description [0.19s]                   
Starting >>> moveit_task_constructor_msgs
Finished <<< moveit_task_constructor_msgs [0.73s]                      
Starting >>> rviz_marker_tools
Finished <<< rviz_marker_tools [0.24s]                   
Starting >>> kortex_description
Finished <<< kortex_description [0.19s]                    
Starting >>> moveit_resources_pr2_description
Finished <<< moveit_resources_pr2_description [0.21s]                    
Starting >>> moveit_core
Finished <<< moveit_core [0.60s]                       
Starting >>> moveit_ros_occupancy_map_monitor
Finished <<< moveit_ros_occupancy_map_monitor [0.28s]                    
Starting >>> moveit_ros_planning
Finished <<< moveit_ros_planning [0.41s]                      
Starting >>> moveit_kinematics
Finished <<< moveit_kinematics [0.31s]                    
Starting >>> moveit_ros_move_group
Finished <<< moveit_ros_move_group [0.35s]                       
Starting >>> moveit_ros_warehouse
Finished <<< moveit_ros_warehouse [0.31s]                      
Starting >>> moveit_ros_robot_interaction
Finished <<< moveit_ros_robot_interaction [0.29s]                      
Starting >>> moveit_simple_controller_manager
Finished <<< moveit_simple_controller_manager [0.25s]                        
Starting >>> moveit_ros_planning_interface
Finished <<< moveit_ros_planning_interface [0.30s]                     
Starting >>> moveit_ros_visualization
Finished <<< moveit_ros_visualization [0.56s]                       
Starting >>> moveit_planners_ompl
Finished <<< moveit_planners_ompl [0.32s]                       
Starting >>> moveit_setup_framework
Finished <<< moveit_setup_framework [0.31s]                     
Starting >>> moveit_planners_stomp
Finished <<< moveit_planners_stomp [0.27s]                     
Starting >>> moveit_setup_app_plugins
Finished <<< moveit_setup_app_plugins [0.38s]                        
Starting >>> moveit_setup_controllers
Finished <<< moveit_setup_controllers [0.42s]                        
Starting >>> moveit_setup_core_plugins
Finished <<< moveit_setup_core_plugins [0.34s]                      
Starting >>> moveit_setup_srdf_plugins
Finished <<< moveit_setup_srdf_plugins [0.43s]                       
Starting >>> moveit_setup_assistant
Finished <<< moveit_setup_assistant [0.31s]                       
Starting >>> moveit_resources_prbt_support
Finished <<< moveit_resources_prbt_support [0.20s]                     
Starting >>> moveit_resources_prbt_ikfast_manipulator_plugin
Finished <<< moveit_resources_prbt_ikfast_manipulator_plugin [0.27s]
Starting >>> moveit_plugins
Finished <<< moveit_plugins [0.20s]                     
Starting >>> moveit_ros_benchmarks
Finished <<< moveit_ros_benchmarks [0.30s]                     
Starting >>> kortex_api
Finished <<< kortex_api [0.20s]                     
Starting >>> rviz_visual_tools
Finished <<< rviz_visual_tools [0.44s]                       
Starting >>> serial
Finished <<< serial [0.22s]                     
Starting >>> chomp_motion_planner
Finished <<< chomp_motion_planner [0.28s]                        
Starting >>> moveit_ros_perception
Finished <<< moveit_ros_perception [0.31s]                       
Starting >>> moveit_resources_prbt_moveit_config
Finished <<< moveit_resources_prbt_moveit_config [0.21s]                     
Starting >>> moveit_ros
Finished <<< moveit_ros [0.21s]                     
Starting >>> kortex_driver
Finished <<< kortex_driver [0.25s]                     
Starting >>> robotiq_driver
Finished <<< robotiq_driver [0.31s]                     
Starting >>> pick_ik
--- stderr: pick_ik                                
/home/ym/ws_moveit2test2/build/pick_ik/tests/test-pick_ik: symbol lookup error: /opt/ros/humble/lib/libpick_ik_plugin.so: undefined symbol: _ZN10kinematics14KinematicsBase6LOGGERE
CMake Error at /home/ym/ws_moveit2test2/build/pick_ik/_deps/catch2-src/extras/CatchAddTests.cmake:60 (message):
  Error running test executable
  '/home/ym/ws_moveit2test2/build/pick_ik/tests/test-pick_ik':

    Result: 127
    Output: 

gmake[2]: *** [tests/CMakeFiles/test-pick_ik.dir/build.make:340：tests/test-pick_ik] 错误 1
gmake[2]: *** 正在删除文件“tests/test-pick_ik”
gmake[1]: *** [CMakeFiles/Makefile2:244：tests/CMakeFiles/test-pick_ik.dir/all] 错误 2
gmake: *** [Makefile:146：all] 错误 2
---
Failed   <<< pick_ik [0.37s, exited with code 2]

Summary: 43 packages finished [17.8s]
  1 package failed: pick_ik
  2 packages had stderr output: moveit_configs_utils pick_ik
  25 packages not processed

who can tell me How to experience all the features of moveit2_tutotials,thanks in advance.

**Comment by sea-bass** [comment]
As discussed in https://github.com/PickNikRobotics/pick_ik/issues/65 and https://github.com/PickNikRobotics/pick_ik/issues/64, could you try removing your MoveIt binary installs that may be lingering? Thanks!

**Comment by sea-bass** [comment]
There are no binaries for MoveIt Task Constructor. But it seems like you may have mismatched versions of both that repo and `moveit_visual_tools`. Can you make sure you've got the `ros2` branches of both of those, respectively?

**Comment by yangming517** [comment]
@sea-bass Hi,I have big problem.Though I successfully build,I find that I almost meet the same problem " planning scene requesting initial scene failed"every time when i launch the "demo.launch.py""mtc_demo.launch.py"and so forth.
when i launch demo.launch.py,the terminal shows above
`ym@ym-PC:~/ws_moveit2test2$ ros2 launch moveit2_tutorials demo.launch.py 
[INFO] [launch]: All log files can be found below /home/ym/.ros/log/2024-03-12-18-44-23-219971-ym-PC-54476
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [rviz2-1]: process started with pid [54477]
[INFO] [static_transform_publisher-2]: process started with pid [54479]
[INFO] [robot_state_publisher-3]: process started with pid [54481]
[INFO] [move_group-4]: process started with pid [54483]
[INFO] [ros2_control_node-5]: process started with pid [54485]
[INFO] [spawner-6]: process started with pid [54487]
[INFO] [spawner-7]: process started with pid [54489]
[INFO] [spawner-8]: process started with pid [54491]
[static_transform_publisher-2] [INFO] [1710240263.707630945] [static_transform_publisher]: Spinning until stopped - publishing transform
[static_transform_publisher-2] translation: ('0.000000', '0.000000', '0.000000')
[static_transform_publisher-2] rotation: ('0.000000', '0.000000', '0.000000', '1.000000')
[static_transform_publisher-2] from 'world' to 'base_link'
[robot_state_publisher-3] [INFO] [1710240263.714744396] [robot_state_publisher]: got segment base_link
[robot_state_publisher-3] [INFO] [1710240263.714831188] [robot_state_publisher]: got segment bracelet_link
[robot_state_publisher-3] [INFO] [1710240263.714844536] [robot_state_publisher]: got segment end_effector_link
[robot_state_publisher-3] [INFO] [1710240263.714853070] [robot_state_publisher]: got segment forearm_link
[robot_state_publisher-3] [INFO] [1710240263.714860779] [robot_state_publisher]: got segment half_arm_1_link
[robot_state_publisher-3] [INFO] [1710240263.714868104] [robot_state_publisher]: got segment half_arm_2_link
[robot_state_publisher-3] [INFO] [1710240263.714875550] [robot_state_publisher]: got segment robotiq_85_base_link
[robot_state_publisher-3] [INFO] [1710240263.714883530] [robot_state_publisher]: got segment robotiq_85_left_finger_link
[robot_state_publisher-3] [INFO] [1710240263.714891318] [robot_state_publisher]: got segment robotiq_85_left_finger_tip_link
[robot_state_publisher-3] [INFO] [1710240263.714899085] [robot_state_publisher]: got segment robotiq_85_left_inner_knuckle_link
[robot_state_publisher-3] [INFO] [1710240263.714906223] [robot_state_publisher]: got segment robotiq_85_left_knuckle_link
[robot_state_publisher-3] [INFO] [1710240263.714913488] [robot_state_publisher]: got segment robotiq_85_right_finger_link
[robot_state_publisher-3] [INFO] [1710240263.714921052] [robot_state_publisher]: got segment robotiq_85_right_finger_tip_link
[robot_state_publisher-3] [INFO] [1710240263.714928568] [robot_state_publisher]: got segment robotiq_85_right_inner_knuckle_link
[robot_state_publisher-3] [INFO] [1710240263.714935950] [robot_state_publisher]: got segment robotiq_85_right_knuckle_link
[robot_state_publisher-3] [INFO] [1710240263.714943704] [robot_state_publisher]: got segment shoulder_link
[robot_state_publisher-3] [INFO] [1710240263.714950948] [robot_state_publisher]: got segment spherical_wrist_1_link
[robot_state_publisher-3] [INFO] [1710240263.714958836] [robot_state_publisher]: got segment spherical_wrist_2_link
[robot_state_publisher-3] [INFO] [1710240263.714966297] [robot_state_publisher]: got segment world
[ros2_control_node-5] [INFO] [1710240263.726391030] [controller_manager]: Subscribing to '~/robot_description' topic for robot description file.
[ros2_control_node-5] [INFO] [1710240263.728860363] [controller_manager]: update rate is 1000 Hz
[ros2_control_node-5] [INFO] [1710240263.728981494] [controller_manager]: RT kernel is recommended for better performance
[ros2_control_node-5] [INFO] [1710240263.729455679] [controller_manager]: Received robot description file.
[ros2_control_node-5] [INFO] [1710240263.729743812] [resource_manager]: Loading hardware 'KortexMultiInterfaceHardware' 
[ros2_control_node-5] [INFO] [1710240263.730274349] [resource_manager]: Initialize hardware 'KortexMultiInterfaceHardware' 
[ros2_control_node-5] [WARN] [1710240263.730290356] [mock_generic_system]: Parameter 'fake_sensor_commands' has been deprecated from usage. Use'mock_sensor_commands' instead.
[ros2_control_node-5] [WARN] [1710240263.730302076] [mock_generic_system]: Parsing of optional initial interface values failed or uses a deprecated format. Add initial values for every state interface in the ros2_control.xacro. For example: 
[ros2_control_node-5] <state_interface name="velocity"> 
[ros2_control_node-5]   <param name="initial_value">0.0</param> 
[ros2_control_node-5] </state_interface>
[ros2_control_node-5] [INFO] [1710240263.730309566] [resource_manager]: Successful initialization of hardware 'KortexMultiInterfaceHardware'
[ros2_control_node-5] [INFO] [1710240263.730324238] [resource_manager]: Loading hardware 'RobotiqGripperHardwareInterface' 
[ros2_control_node-5] [INFO] [1710240263.730331867] [resource_manager]: Initialize hardware 'RobotiqGripperHardwareInterface' 
[ros2_control_node-5] [WARN] [1710240263.730337605] [mock_generic_system]: Parameter 'fake_sensor_commands' has been deprecated from usage. Use'mock_sensor_commands' instead.
[ros2_control_node-5] [INFO] [1710240263.730346725] [resource_manager]: Successful initialization of hardware 'RobotiqGripperHardwareInterface'
[ros2_control_node-5] [INFO] [1710240263.730384239] [resource_manager]: 'configure' hardware 'KortexMultiInterfaceHardware' 
[ros2_control_node-5] [INFO] [1710240263.730391499] [resource_manager]: Successful 'configure' of hardware 'KortexMultiInterfaceHardware'
[ros2_control_node-5] [INFO] [1710240263.730397493] [resource_manager]: 'activate' hardware 'KortexMultiInterfaceHardware' 
[ros2_control_node-5] [INFO] [1710240263.730400515] [resource_manager]: Successful 'activate' of hardware 'KortexMultiInterfaceHardware'
[ros2_control_node-5] [INFO] [1710240263.730402931] [resource_manager]: 'configure' hardware 'RobotiqGripperHardwareInterface' 
[ros2_control_node-5] [INFO] [1710240263.730405409] [resource_manager]: Successful 'configure' of hardware 'RobotiqGripperHardwareInterface'
[ros2_control_node-5] [INFO] [1710240263.730409242] [resource_manager]: 'activate' hardware 'RobotiqGripperHardwareInterface' 
[ros2_control_node-5] [INFO] [1710240263.730411783] [resource_manager]: Successful 'activate' of hardware 'RobotiqGripperHardwareInterface'
[move_group-4] [INFO] [1710240263.738222778] [move_group.moveit.RDFLoader]: Loaded robot model in 0.00286704 seconds
[move_group-4] [INFO] [1710240263.738272664] [move_group.moveit.robot_model]: Loading robot model 'gen3'...
[move_group-4] [INFO] [1710240263.738282160] [move_group.moveit.robot_model]: No root/virtual joint specified in SRDF. Assuming fixed joint
[ros2_control_node-5] [INFO] [1710240263.739422999] [controller_manager]: Received robot description file.
[ros2_control_node-5] [WARN] [1710240263.739450338] [controller_manager]: ResourceManager has already loaded an urdf file. Ignoring attempt to reload a robot description file.
[move_group-4] [INFO] [1710240263.827337886] [move_group.moveit.kdl_kinematics_plugin]: Joint weights for group 'manipulator': 1 1 1 1 1 1 1
[ros2_control_node-5] [INFO] [1710240263.912872569] [controller_manager]: Loading controller 'joint_trajectory_controller'
[ros2_control_node-5] [WARN] [1710240263.919099618] [joint_trajectory_controller]: [Deprecated]: "allow_nonzero_velocity_at_trajectory_end" is set to true. The default behavior will change to false.
[spawner-7] [INFO] [1710240263.935921185] [spawner_joint_trajectory_controller]: Loaded joint_trajectory_controller
[ros2_control_node-5] [INFO] [1710240263.936491145] [controller_manager]: Configuring controller 'joint_trajectory_controller'
[ros2_control_node-5] [INFO] [1710240263.936621025] [joint_trajectory_controller]: No specific joint names are used for command interfaces. Using 'joints' parameter.
[ros2_control_node-5] [INFO] [1710240263.936639162] [joint_trajectory_controller]: Command interfaces are [position] and state interfaces are [position velocity].
[ros2_control_node-5] [INFO] [1710240263.936648320] [joint_trajectory_controller]: Using 'splines' interpolation method.
[ros2_control_node-5] [INFO] [1710240263.937306532] [joint_trajectory_controller]: Controller state will be published at 100.00 Hz.
[ros2_control_node-5] [INFO] [1710240263.939357583] [joint_trajectory_controller]: Action status changes will be monitored at 20.00 Hz.
[ros2_control_node-5] [INFO] [1710240263.944253718] [controller_manager]: Loading controller 'joint_state_broadcaster'
[spawner-7] [INFO] [1710240263.944744523] [spawner_joint_trajectory_controller]: Configured and activated joint_trajectory_controller
[ros2_control_node-5] [INFO] [1710240263.949035440] [controller_manager]: Loading controller 'robotiq_gripper_controller'
[spawner-6] [INFO] [1710240263.960162765] [spawner_joint_state_broadcaster]: Loaded joint_state_broadcaster
[ros2_control_node-5] [INFO] [1710240263.960666739] [controller_manager]: Configuring controller 'joint_state_broadcaster'
[ros2_control_node-5] [INFO] [1710240263.960714797] [joint_state_broadcaster]: 'joints' or 'interfaces' parameter is empty. All available state interfaces will be published
[spawner-6] [INFO] [1710240263.964604401] [spawner_joint_state_broadcaster]: Configured and activated joint_state_broadcaster
[spawner-8] [INFO] [1710240263.965495807] [spawner_robotiq_gripper_controller]: Loaded robotiq_gripper_controller
[ros2_control_node-5] [INFO] [1710240263.966004396] [controller_manager]: Configuring controller 'robotiq_gripper_controller'
[ros2_control_node-5] [INFO] [1710240263.966065365] [robotiq_gripper_controller]: Action status changes will be monitored at 20Hz.
[spawner-8] [INFO] [1710240263.970682297] [spawner_robotiq_gripper_controller]: Configured and activated robotiq_gripper_controller
[move_group-4] [INFO] [1710240264.040375491] [move_group.moveit.planning_scene_monitor]: Publishing maintained planning scene on 'monitored_planning_scene'
[move_group-4] [INFO] [1710240264.040469198] [move_group.moveit.moveit_cpp]: Listening to 'joint_states' for joint states
[move_group-4] [INFO] [1710240264.040715992] [move_group.moveit.current_state_monitor]: Listening to joint states on topic 'joint_states'
[move_group-4] [INFO] [1710240264.041006669] [move_group.moveit.planning_scene_monitor]: Listening to '/attached_collision_object' for attached collision objects
[move_group-4] [INFO] [1710240264.041014457] [move_group.moveit.planning_scene_monitor]: Stopping existing planning scene publisher.
[move_group-4] [INFO] [1710240264.041094113] [move_group.moveit.planning_scene_monitor]: Stopped publishing maintained planning scene.
[move_group-4] [INFO] [1710240264.041673948] [move_group.moveit.planning_scene_monitor]: Publishing maintained planning scene on 'monitored_planning_scene'
[move_group-4] [INFO] [1710240264.041729101] [move_group.moveit.planning_scene_monitor]: Starting planning scene monitor
[move_group-4] Stack trace (most recent call last) in thread 54590:
[move_group-4] [INFO] [1710240264.042347021] [move_group.moveit.planning_scene_monitor]: Listening to '/planning_scene'
[move_group-4] [INFO] [1710240264.042356734] [move_group.moveit.planning_scene_monitor]: Starting world geometry update monitor for collision objects, attached objects, octomap updates.
[move_group-4] [INFO] [1710240264.042600480] [move_group.moveit.planning_scene_monitor]: Listening to 'collision_object'
[move_group-4] [INFO] [1710240264.042858382] [move_group.moveit.planning_scene_monitor]: Listening to 'planning_scene_world' for planning scene world geometry
[move_group-4] #9    Object "", at 0xffffffffffffffff, in 
[move_group-4] [WARN] [1710240264.043507000] [move_group.moveit.occupancy_map_monitor]: Resolution not specified for Octomap. Assuming resolution = 0.1 instead
[move_group-4] [ERROR] [1710240264.043518360] [move_group.moveit.occupancy_map_monitor]: No 3D sensor plugin(s) defined for octomap updates
[move_group-4] #8    Source "../sysdeps/unix/sysv/linux/x86_64/clone3.S", line 81, in __clone3 [0x7f901532684f]
[move_group-4] #7    Source "./nptl/pthread_create.c", line 442, in start_thread [0x7f9015294ac2]
[move_group-4] #6    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30", at 0x7f90156dc252, in 
[move_group-4] #5    Object "/opt/ros/humble/lib/librclcpp.so", at 0x7f9015af88af, in rclcpp::executors::SingleThreadedExecutor::spin()
[move_group-4] #4    Object "/opt/ros/humble/lib/librclcpp.so", at 0x7f9015af0fbe, in rclcpp::Executor::execute_any_executable(rclcpp::AnyExecutable&)
[move_group-4] #3    Object "/opt/ros/humble/lib/librclcpp.so", at 0x7f9015af07bb, in rclcpp::Executor::execute_subscription(std::shared_ptr<rclcpp::SubscriptionBase>)
[move_group-4] #2    Object "/home/ym/ws_moveit2test2/install/moveit_ros_planning/lib/libmoveit_planning_scene_monitor.so.2.9.0", at 0x7f9015e0a944, in rclcpp::Subscription<sensor_msgs::msg::JointState_<std::allocator<void> >, std::allocator<void>, sensor_msgs::msg::JointState_<std::allocator<void> >, sensor_msgs::msg::JointState_<std::allocator<void> >, rclcpp::message_memory_strategy::MessageMemoryStrategy<sensor_msgs::msg::JointState_<std::allocator<void> >, std::allocator<void> > >::handle_message(std::shared_ptr<void>&, rclcpp::MessageInfo const&)
[move_group-4] #1    Object "/home/ym/ws_moveit2test2/install/moveit_ros_planning/lib/libmoveit_planning_scene_monitor.so.2.9.0", at 0x7f9015df8321, in std::__detail::__variant::__gen_vtable_impl<std::__detail::__variant::_Multi_array<std::__detail::__variant::__deduce_visit_result<void> (*)(rclcpp::AnySubscriptionCallback<sensor_msgs::msg::JointState_<std::allocator<void> >, std::allocator<void> >::dispatch(std::shared_ptr<sensor_msgs::msg::JointState_<std::allocator<void> > >, rclcpp::MessageInfo const&)::{lambda(auto:1&&)#1}&&, std::variant<std::function<void (sensor_msgs::msg::JointState_<std::allocator<void> > const&)>, std::function<void (sensor_msgs::msg::JointState_<std::allocator<void> > const&, rclcpp::MessageInfo const&)>, std::function<void (rclcpp::SerializedMessage const&)>, std::function<void (rclcpp::SerializedMessage const&, rclcpp::MessageInfo const&)>, std::function<void (std::unique_ptr<sensor_msgs::msg::JointState_<std::allocator<void> >, std::default_delete<sensor_msgs::msg::JointState_<std::allocator<void> > > >)>, std::function<void (std::unique_ptr<sensor_msgs::msg::JointState_<std::allocator<void> >, std::default_delete<sensor_msgs::msg::JointState_<std::allocator<void> > > >, rclcpp::MessageInfo const&)>, std::function<void (std::unique_ptr<rclcpp::SerializedMessage, std::default_delete<rclcpp::SerializedMessage> >)>, std::function<void (std::unique_ptr<rclcpp::SerializedMessage, std::default_delete<rclcpp::SerializedMessage> >, rclcpp::MessageInfo const&)>, std::function<void (std::shared_ptr<sensor_msgs::msg::JointState_<std::allocator<void> > const>)>, std::function<void (std::shared_ptr<sensor_msgs::msg::JointState_<std::allocator<void> > const>, rclcpp::MessageInfo const&)>, std::function<void (std::shared_ptr<rclcpp::SerializedMessage const>)>, std::function<void (std::shared_ptr<rclcpp::SerializedMessage const>, rclcpp::MessageInfo const&)>, std::function<void (std::shared_ptr<sensor_msgs::msg::JointState_<std::allocator<void> > const> const&)>, std::function<void (std::shared_ptr<sensor_msgs::msg::JointState_<std::allocator<void> > const> const&, rclcpp::MessageInfo const&)>, std::function<void (std::shared_ptr<rclcpp::SerializedMessage const> const&)>, std::function<void (std::shared_ptr<rclcpp::SerializedMessage const> const&, rclcpp::MessageInfo const&)>, std::function<void (std::shared_ptr<sensor_msgs::msg::JointState_<std::allocator<void> > >)>, std::function<void (std::shared_ptr<sensor_msgs::msg::JointState_<std::allocator<void> > >, rclcpp::MessageInfo const&)>, std::function<void (std::shared_ptr<rclcpp::SerializedMessage>)>, std::function<void (std::shared_ptr<rclcpp::SerializedMessage>, rclcpp::MessageInfo const&)> >&)>, std::integer_sequence<unsigned long, 8ul> >::__visit_invoke(rclcpp::AnySubscriptionCallback<sensor_msgs::msg::JointState_<std::allocator<void> >, std::allocator<void> >::dispatch(std::shared_ptr<sensor_msgs::msg::JointState_<std::allocator<void> > >, rclcpp::MessageInfo const&)::{lambda(auto:1&&)#1}&&, std::variant<std::function<void (sensor_msgs::msg::JointState_<std::allocator<void> > const&)>, std::function<void (sensor_msgs::msg::JointState_<std::allocator<void> > const&, rclcpp::MessageInfo const&)>, std::function<void (rclcpp::SerializedMessage const&)>, std::function<void (rclcpp::SerializedMessage const&, rclcpp::MessageInfo const&)>, std::function<void (std::unique_ptr<sensor_msgs::msg::JointState_<std::allocator<void> >, std::default_delete<sensor_msgs::msg::JointState_<std::allocator<void> > > >)>, std::function<void (std::unique_ptr<sensor_msgs::msg::JointState_<std::allocator<void> >, std::default_delete<sensor_msgs::msg::JointState_<std::allocator<void> > > >, rclcpp::MessageInfo const&)>, std::function<void (std::unique_ptr<rclcpp::SerializedMessage, std::default_delete<rclcpp::SerializedMessage> >)>, std::function<void (std::unique_ptr<rclcpp::SerializedMessage, std::default_delete<rclcpp::SerializedMessage> >, rclcpp::MessageInfo const&)>, std::function<void (std::shared_ptr<sensor_msgs::msg::JointState_<std::allocator<void> > const>)>, std::function<void (std::shared_ptr<sensor_msgs::msg::JointState_<std::allocator<void> > const>, rclcpp::MessageInfo const&)>, std::function<void (std::shared_ptr<rclcpp::SerializedMessage const>)>, std::function<void (std::shared_ptr<rclcpp::SerializedMessage const>, rclcpp::MessageInfo const&)>, std::function<void (std::shared_ptr<sensor_msgs::msg::JointState_<std::allocator<void> > const> const&)>, std::function<void (std::shared_ptr<sensor_msgs::msg::JointState_<std::allocator<void> > const> const&, rclcpp::MessageInfo const&)>, std::function<void (std::shared_ptr<rclcpp::SerializedMessage const> const&)>, std::function<void (std::shared_ptr<rclcpp::SerializedMessage const> const&, rclcpp::MessageInfo const&)>, std::function<void (std::shared_ptr<sensor_msgs::msg::JointState_<std::allocator<void> > >)>, std::function<void (std::shared_ptr<sensor_msgs::msg::JointState_<std::allocator<void> > >, rclcpp::MessageInfo const&)>, std::function<void (std::shared_ptr<rclcpp::SerializedMessage>)>, std::function<void (std::shared_ptr<rclcpp::SerializedMessage>, rclcpp::MessageInfo const&)> >&)
[move_group-4] #0    Object "/home/ym/ws_moveit2test2/install/moveit_ros_planning/lib/libmoveit_planning_scene_monitor.so.2.9.0", at 0x7f9015de71ae, in planning_scene_monitor::CurrentStateMonitor::jointStateCallback(std::shared_ptr<sensor_msgs::msg::JointState_<std::allocator<void> > const> const&)
[move_group-4] Segmentation fault (Address not mapped to object [0x2])
[ERROR] [move_group-4]: process has died [pid 54483, exit code -11, cmd '/home/ym/ws_moveit2test2/install/moveit_ros_move_group/lib/moveit_ros_move_group/move_group --ros-args --params-file /tmp/launch_params_uykhztpu'].
[rviz2-1] [INFO] [1710240264.168374614] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-1] [INFO] [1710240264.168470259] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[rviz2-1] [INFO] [1710240264.188281595] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-1] [WARN] [1710240264.257618254] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[rviz2-1] Warning: class_loader.impl: SEVERE WARNING!!! A namespace collision has occurred with plugin factory for class rviz_default_plugins::displays::InteractiveMarkerDisplay. New factory will OVERWRITE existing one. This situation occurs when libraries containing plugins are directly linked against an executable (the one running right now generating this message). Please separate plugins out into their own library or just don't link against the library and use either class_loader::ClassLoader/MultiLibraryClassLoader to open.
[rviz2-1]          at line 253 in /opt/ros/humble/include/class_loader/class_loader/class_loader_core.hpp
[rviz2-1] [INFO] [1710240264.279507382] [rviz2.RDFLoader]: Loaded robot model in 0.00250975 seconds
[rviz2-1] [INFO] [1710240264.279544911] [rviz2.robot_model]: Loading robot model 'gen3'...
[rviz2-1] [INFO] [1710240264.279556066] [rviz2.robot_model]: No root/virtual joint specified in SRDF. Assuming fixed joint
[INFO] [spawner-7]: process has finished cleanly [pid 54489]
[INFO] [spawner-6]: process has finished cleanly [pid 54487]
[INFO] [spawner-8]: process has finished cleanly [pid 54491]
[rviz2-1] [ERROR] [1710240267.514439739] [rviz2.motion_planning_frame]: Action server: /recognize_objects not available
[rviz2-1] [INFO] [1710240267.524213800] [rviz2.motion_planning_frame]: MoveGroup namespace changed: / -> . Reloading params.
[rviz2-1] [INFO] [1710240267.570740908] [rviz2.RDFLoader]: Loaded robot model in 0.00192848 seconds
[rviz2-1] [INFO] [1710240267.570761371] [rviz2.robot_model]: Loading robot model 'gen3'...
[rviz2-1] [INFO] [1710240267.570765426] [rviz2.robot_model]: No root/virtual joint specified in SRDF. Assuming fixed joint
[rviz2-1] [INFO] [1710240267.657469920] [rviz2.kdl_kinematics_plugin]: Joint weights for group 'manipulator': 1 1 1 1 1 1 1
[rviz2-1] [INFO] [1710240267.885239385] [rviz2.planning_scene_monitor]: Starting planning scene monitor
[rviz2-1] [INFO] [1710240267.885982787] [rviz2.planning_scene_monitor]: Listening to '/monitored_planning_scene'
[rviz2-1] [INFO] [1710240267.888174483] [rviz2.planning_scene_monitor]: Starting planning scene monitor
[rviz2-1] [INFO] [1710240267.888808974] [rviz2.planning_scene_monitor]: Listening to '/monitored_planning_scene'
[rviz2-1] [INFO] [1710240267.894678020] [interactive_marker_display_94250389603632]: Connected on namespace: /rviz_moveit_motion_planning_display/robot_interaction_interactive_marker_topic
[rviz2-1] [INFO] [1710240267.898246137] [rviz2.moveit_ros_robot_interaction]: No active joints or end effectors found for group 'gripper'. Make sure that kinematics.yaml is loaded in this node's namespace.
[rviz2-1] [INFO] [1710240267.898928858] [rviz2.moveit_ros_robot_interaction]: No active joints or end effectors found for group 'gripper'. Make sure that kinematics.yaml is loaded in this node's namespace.
[rviz2-1] [INFO] [1710240267.916629740] [interactive_marker_display_94250389603632]: Sending request for interactive markers
[rviz2-1] [INFO] [1710240267.948643382] [interactive_marker_display_94250389603632]: Service response received for initialization
[rviz2-1] [INFO] [1710240272.888635682] [rviz2.planning_scene_monitor]: Failed to call service get_planning_scene, have you launched move_group or called psm.providePlanningSceneService()?
[rviz2-1] [INFO] [1710240272.901257916] [rviz2.planning_scene_monitor]: Failed to call service get_planning_scene, have you launched move_group or called psm.providePlanningSceneService()?
[rviz2-1] [INFO] [1710240272.901300927] [rviz2.motion_planning_frame]: group gripper
[rviz2-1] [INFO] [1710240272.901305756] [rviz2.motion_planning_frame]: Constructing new MoveGroup connection for group 'gripper' in namespace ''
and the rviz interface show that 
![rviz](https://github.com/ros-planning/moveit2_tutorials/assets/125530846/3ff68c83-38ed-4257-8d75-f875da72b781)

`does it related to  the moveit2 installation method of binary.i install moveit2 by binary .

**Comment by Mactarvish** [comment]
Same error (havn't try https://github.com/moveit/moveit2_tutorials/issues/719 mentioned above yet) but I checked the source code and there're exactly `trajectory` `description` intead of `trajectory_` `descrition_` , why compiler found `xx_` not `xx` ? Cannot understand
