### ISSUE TITLE
Something wrong in "Pick and Place with MoveIt Task Constructor" :   'rviz/Orbit', could not be loaded.

### ISSUE THREAD

**Issue by zjjackie** [ros-planning/moveit2_tutorials#893]
I was studying "Pick and Place with MoveIt Task Constructor" , 

when I run "ros2 launch moveit_task_constructor_demo demo.launch.py "

I found an error:
"The class required for this view controller, 'rviz/Orbit', could not be loaded.
Error:
According to the loaded plugin descriptions the class rviz/Orbit with base class type rviz_common::ViewController does not exist. Declared types are rviz_default_plugins/FPS rviz_default_plugins/Orbit rviz_default_plugins/ThirdPersonFollower rviz_default_plugins/TopDownOrtho rviz_default_plugins/XYOrbit"

![1](https://github.com/ros-planning/moveit2_tutorials/assets/130440590/8719fd5c-0283-4860-b1c6-47047d568112)
![2](https://github.com/ros-planning/moveit2_tutorials/assets/130440590/42549c69-9561-431e-833a-5ad0254b3829)

my environment
ROS Distro: Humble
OS Version: Ubuntu 22.04

**Comment by rhaschke** [comment]
The humble branch was on an old commit. Please try again.
